In [25]:
import numpy as np

print(np.__version__)

2.2.6


In [26]:
arr = np.array([10, 20, 30, 40, 50, 60])
print(arr)

[10 20 30 40 50 60]


In [27]:
print(type(arr))

<class 'numpy.ndarray'>


**Array Arithmatic**

In [28]:
arth = np.array([1, 2, 3, 4])
print(arth * 2)

[2 4 6 8]


In [29]:
print(arth + 5)

[6 7 8 9]


In [30]:
print(arth - 1)

[0 1 2 3]


In [31]:
print(arth % 2)

[1 0 1 0]


In [32]:
print(arth / 2)

[0.5 1.  1.5 2. ]


In [33]:
print(arth[1])

2


In [34]:
print(arth[1:3])

[2 3]


**Useful Array Creation Functions**

In [35]:
zr = np.zeros(5)
print(zr)

[0. 0. 0. 0. 0.]


In [36]:
ones = np.ones(5)
print(ones)

[1. 1. 1. 1. 1.]


In [37]:
arr = np.arange(1, 11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


**Statistics**

In [38]:
array = np.array([10,20,30,40])
print(array.mean())

25.0


In [39]:
arr = np.array([1,6,8,5])
print(arr.max())

8


In [40]:
print(arr.min())

1


In [41]:
print(arr.sum())

20
